<html>
<head>
    <title>РЭУ имени Г.В. Плеханова</title>
    <meta http-equiv="Content-Type" content="text/html; charset=windows-1251">
    <META name="Author" content="http://ailus.ru">
    <meta name="Copyright" content="http://ailus.ru">
</head>
<body leftmargin="0" topmargin="0" marginwidth="0" marginheight="0" rightmargin="0" bottommargin="0" bgcolor="#ffffff">
<link href="index.css" type="text/css" rel="STYLESHEET">
<table border=1 width=100% height=20%>
    <tr>
        <td width=100% height=20% align=center> Лабораторные работы по курсу "Разработка интернет приложений в сфере
            коммерциии посредством PHP и MySQL" <br> Студента группы ПИс-161: Мельникова Ильи Ивановича <br> Проверил:
            к.т.н. доц. Назимов А.С.
        </td>
</table>
<table border=1 width=100%>
    <td width=30% align=left valign=top>
        <a href="/formorders/OrderForm.php"> Лабораторная работа №1</a>
        <br><br>
        <a href="/formorders/OrderForm2.php"> Лабораторная работа №2</a>
        <br><br>
        <a href="/formorders/OrderForm3.php"> Лабораторная работа №3</a>
        <br><br>
        <a href="/formorders/OrderForm4.php"> Лабораторная работа №4</a>
        <br><br>
        <a href="/index_5.php"> Лабораторная работа №5</a>
        <br><br>
    </td>
    <td width=70% align=center>
